### ISSUE TITLE
Makemedia.exe not Found and still not provided Axinom DRM customer portal

### ISSUE THREAD

**Issue by saqibkafeel** [Axinom/drm-quick-start#4]
Make it Easy And also provide login session on your main site ! 
And Also tell me whats its cost after testing Month ?

**Comment by saqibkafeel** [comment]
![image](https://cloud.githubusercontent.com/assets/6615261/23207475/47e8acdc-f8a6-11e6-80fc-ad0d37e3833b.png)

after it no one  mail recived ! for drm customer portal !

**Comment by sandersaares** [comment]
I hear this was resolved via other channels. Please reopen if still and issue.

**Comment by simonasB** [comment]
Hello, Makemedia.exe is still not available. I have tried to search for it today.

**Comment by jurgenj** [comment]
@simonasB In order to get access you need to sign the NDA first and then you can get the access to production documetnation and other details.

**Comment by simonasB** [comment]
I have signed NDA for evaluation account and I have access to it. Isn't enough?
